# Generated by Django 5.2.18 on 2026-10-08 22:51

import django.db.models.deletion
from django.db import migrations, models


def map_old_statuses(apps, schema_editor):
    WorkOrder = apps.get_model('mes', 'WorkOrder')
    WorkOrder.objects.filter(status='planned').update(status='entered')
    WorkOrder.objects.filter(status='done').update(status='complete')


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('entered', 'Entered'), ('allocated', 'Allocated'), ('issued', 'Issued'), ('in_progress', 'In progress'), ('qa', 'QA'), ('complete', 'Complete')], default='entered', max_length=20),
        ),
        migrations.AddField(
            model_name='workorder',
            name='operative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='mes.operative'),
        ),
        migrations.RunPython(map_old_statuses, migrations.RunPython.noop),
    ]
