# Generated by Django 5.2.18 on 2026-10-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0002_lifecycle_operative_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='est_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
