# Generated by Django 5.2.18 on 2026-10-08 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0004_production_technician'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('order_date', models.DateField()),
                ('customer', models.CharField(max_length=200)),
                ('customer_ref', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-order_date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='mes.customerorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mes.product')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='mes.workorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
