# Generated by Django 5.2.18 on 2026-10-08 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0006_unit_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=60, unique=True)),
                ('procedure', models.CharField(max_length=30)),
                ('serial', models.CharField(max_length=50)),
                ('build_reference', models.CharField(blank=True, max_length=50)),
                ('operator_name', models.CharField(blank=True, max_length=100)),
                ('test_date', models.DateField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('overall_result', models.CharField(default='PASS', max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_reports', to='mes.product')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_reports', to='mes.productiontechnician')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_reports', to='mes.unit')),
            ],
            options={
                'ordering': ['-test_date', '-submitted_at', 'report_id'],
            },
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('section', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=10)),
                ('criteria', models.TextField()),
                ('result', models.CharField(blank=True, max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('sign_off', models.CharField(blank=True, max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='mes.testreport')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
