# Generated by Django 5.2.18 on 2026-10-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0008_catalogue_bom_machines_defects'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='range_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='rrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rrp_estimated',
            field=models.BooleanField(default=False),
        ),
    ]
