# Generated by Django 5.2.18 on 2026-10-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0009_product_rrp_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_part_no',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
