# Generated by Django 5.2.18 on 2026-10-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0010_product_stock_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
