"""Render the app as a static, read-only website (for GitHub Pages or any file host).

It crawls every page the way a visitor would, using the data currently in the database, and writes plain
HTML with relative links. Search, sorting, filtering and CSV export are done in the browser by
mes/static_site/demo.js; buttons that change data are switched off.

    manage.py build_static_site --out site

Run it against a freshly seeded database (scripts/build_static_site.py does the whole job). It never
touches the live app: pages are rendered in-process with MES_STATIC_EXPORT switched on.
"""
import json
import posixpath
import re
import shutil
from collections import deque
from html import unescape
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urljoin, urlsplit

from django.core.management.base import BaseCommand, CommandError
from django.test import Client
from django.test.utils import override_settings

from mes.models import ProductionTechnician, Unit, Workstation

ORIGIN = "http://localhost"
MARKER = ".static-site"
MAX_PAGES = 5000
TAG = re.compile(r"<(a|form|button)\b[^>]*>", re.I)
LINK = re.compile(r"<a\b[^>]*?\bhref=\"([^\"]*)\"", re.I)


def resolve(href, current):
    """(path, sorted query pairs, fragment) for an on-site link, or None for external/anchor links."""
    href = unescape(href)
    if not href or href.startswith(("#", "mailto:", "javascript:", "data:")):
        return None
    parts = urlsplit(urljoin(ORIGIN + current, href))
    if parts.netloc != "localhost":
        return None
    return parts.path, sorted(parse_qsl(parts.query, keep_blank_values=False)), parts.fragment


def make_key(path, pairs):
    return path + ("?" + urlencode(pairs) if pairs else "")


def wanted(path, pairs):
    """Crawl rules: skip the admin, paging/sorting variants (the browser does those) and runaway timeline shifts."""
    names = {name for name, _ in pairs}
    if path.startswith("/admin") or names & {"sort", "dir", "page"}:
        return False
    if path == "/timeline/":
        values = dict(pairs)
        return names <= {"shift"} and abs(int(values.get("shift", 0))) <= 8
    return True


def file_for(key):
    path, _, query = key.partition("?")
    folder = path.strip("/")
    stem = "index" if not query else "index--" + re.sub(r"[^A-Za-z0-9._-]+", "-", query).strip("-")
    return (folder + "/" if folder else "") + stem + (".csv" if "format=csv" in query else ".html")


class Command(BaseCommand):
    help = "Render the app as a static, read-only site (for GitHub Pages)."

    def add_arguments(self, parser):
        parser.add_argument("--out", default="site", help="output directory (default: site)")
        parser.add_argument("--clean", action="store_true", help="empty the output directory first (only if it was made by this command)")

    def handle(self, *args, out="site", clean=False, **options):
        out_dir = Path(out)
        if out_dir.exists() and clean:
            if not (out_dir / MARKER).exists():
                raise CommandError(f"{out_dir} was not created by build_static_site; refusing to delete it.")
            shutil.rmtree(out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        with override_settings(MES_STATIC_EXPORT=True, ALLOWED_HOSTS=["*"]):
            pages, redirects = self.crawl()
        files = {key: file_for(key) for key in pages}

        def final(key):
            seen = set()
            while key in redirects and key not in seen:
                seen.add(key)
                key = redirects[key]
            return key

        html_keys = [k for k, (kind, _) in pages.items() if kind == "html"]
        for key, (kind, body) in pages.items():
            target = out_dir / files[key]
            target.parent.mkdir(parents=True, exist_ok=True)
            if kind == "csv":
                target.write_bytes(body)
            else:
                target.write_text(self.rewrite(body, key, files, final), encoding="utf-8")

        manifest = {
            "pages": {**{k: files[k] for k in html_keys},
                      **{k: files[final(k)] for k in redirects if final(k) in files and final(k) in html_keys}},
            "serials": {s.lower(): s for s in Unit.objects.values_list("serial", flat=True)},
        }
        (out_dir / "static-manifest.js").write_text("window.__MES_MANIFEST = " + json.dumps(manifest) + ";\n", encoding="utf-8")
        shutil.copy(Path(__file__).resolve().parents[2] / "static_site" / "demo.js", out_dir / "static-demo.js")
        (out_dir / ".nojekyll").write_text("", encoding="utf-8")
        (out_dir / MARKER).write_text("generated by manage.py build_static_site\n", encoding="utf-8")

        size = sum(f.stat().st_size for f in out_dir.rglob("*") if f.is_file())
        self.stdout.write(self.style.SUCCESS(
            f"Wrote {len(html_keys)} pages and {len(pages) - len(html_keys)} CSV files to {out_dir} ({size / 1e6:.1f} MB)."))

    # ---------------------------------------------------------------- crawl

    def crawl(self):
        client = Client(HTTP_HOST="localhost")
        seeds = ["/", "/traceability/"]
        seeds += [f"/board/?station={pk}" for pk in Workstation.objects.values_list("pk", flat=True)]
        seeds += [f"/jobs/?technician={pk}" for pk in ProductionTechnician.objects.values_list("pk", flat=True)]
        seeds += [make_key("/traceability/", [("serial", s)]) for s in Unit.objects.values_list("serial", flat=True)]

        pages, redirects, queue = {}, {}, deque(seeds)
        while queue:
            key = queue.popleft()
            if key in pages or key in redirects:
                continue
            if len(pages) >= MAX_PAGES:
                raise CommandError(f"More than {MAX_PAGES} pages; the crawl is probably looping.")
            response = client.get(key)
            if response.status_code in (301, 302):
                target = resolve(response["Location"], key)
                if target and wanted(target[0], target[1]):
                    redirects[key] = make_key(target[0], target[1])
                    queue.append(redirects[key])
                continue
            if response.status_code != 200:
                self.stderr.write(f"skipped {key} ({response.status_code})")
                continue
            kind = response["Content-Type"]
            if "text/html" in kind:
                html = response.content.decode("utf-8")
                pages[key] = ("html", html)
                for href in LINK.findall(html):
                    found = resolve(href, key)
                    if not found:
                        continue
                    path, pairs, _ = found
                    if {n for n, _ in pairs} == {"q"}:  # table searches are handled in the browser
                        pairs = []
                    if wanted(path, pairs):
                        queue.append(make_key(path, pairs))
            elif "text/csv" in kind:
                pages[key] = ("csv", response.content)
        return pages, redirects

    # -------------------------------------------------------------- rewrite

    def rewrite(self, html, key, files, final):
        here = posixpath.dirname(files[key]) or "."
        root = posixpath.relpath(".", here)
        root = "" if root == "." else root + "/"

        def relative(target_file):
            return posixpath.relpath(target_file, here)

        def map_href(raw):
            """(new href, available) for a link."""
            found = resolve(raw, key)
            if found is None:
                return unescape(raw), True
            path, pairs, fragment = found
            if path.startswith("/admin"):
                return "#", False
            keep = ""
            if {n for n, _ in pairs} == {"q"}:
                keep, pairs = "?" + urlencode(pairs), []
            target = final(make_key(path, pairs))
            if target not in files:
                return "#", False
            return relative(files[target]) + keep + ("#" + fragment if fragment else ""), True

        def tag(match):
            text, name = match.group(0), match.group(1).lower()
            if name == "a":
                href = re.search(r'\bhref="([^"]*)"', text)
                if not href:
                    return text
                new, available = map_href(href.group(1))
                text = text[:href.start(1)] + new.replace("&", "&amp;") + text[href.end(1):]
                return text if available else text[:-1] + ' data-unavailable="1">'
            if name == "form":
                method = (re.search(r'\bmethod="(\w+)"', text, re.I) or [None, "get"])[1].lower()
                action = re.search(r'\saction="([^"]*)"', text)
                if method != "get":
                    return re.sub(r'\saction="[^"]*"', ' action="#"', text)
                found = resolve(action.group(1), key) if action else None
                path = found[0] if found else urlsplit(ORIGIN + key).path  # no action: the form posts to its own page
                text = re.sub(r'\saction="[^"]*"', "", text)
                return text[:-1] + f' data-key-path="{path}">'
            return re.sub(r'\sformaction="[^"]*"', "", text)  # <button formaction=...>

        html = TAG.sub(tag, html)
        html = re.sub(r'<input[^>]*name="csrfmiddlewaretoken"[^>]*>', "", html)
        html = html.replace("</head>", f'<meta name="static-root" content="{root}">\n</head>', 1)
        scripts = f'<script src="{root}static-manifest.js"></script>\n<script src="{root}static-demo.js"></script>\n'
        return html.replace("</body>", scripts + "</body>", 1)
